//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberEligibility.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberEntity
    {
        public int MemberID { get; set; }
        public string MemberName { get; set; }
        public Nullable<int> TechnologyID { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Qualification { get; set; }
        public decimal YearsOfExperience { get; set; }
    
        public virtual TechnologyEntity TechnologyEntity { get; set; }
    }
}
